# Destroy can only be triggered manually on main branch
on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Destroy Terraform"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Navigate to main folder
        run: cd main

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: CDKTF Deploy
        id: destroy
        run: cdktf destroy --auto-approve

      - name: CDKTF Destroy Status
        if: steps.deploy.outcome == 'failure'
        run: exit 1

      - run: |
          echo The Terraform build has been successfully destroyed
