# Provide the current state of Terraform built infrastructure
on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform State"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE }}

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: main/package-lock.json

      - name: Install dependencies
        run: |
          cd main
          npm install
          npm install --global cdktf-cli

      - name: CDKTF Synth
        run: |
          cd main
          cdktf synth -o ../

      - name: Terraform Init
        run: |
          cd stacks/main
          terraform init

      - name: Initialize Wiki folder
        run: |
          mkdir Current-Architecture
          echo \`\`\` >> Current-Architecture/state.md

      - name: Terraform State List
        run: |
          cd stacks/main
          terraform state list >> ../../Current-Architecture/state.md

      - run: |
          echo \`\`\` >> Current-Architecture/state.md
          echo \`\`\` >> Current-Architecture/state.md

      - name: Terraform Show
        run: |
          cd stacks/main
          terraform show >> ../../Current-Architecture/state.md

      - run: |
          echo \`\`\` >> Current-Architecture/state.md

      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "Current-Architecture"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
