# Provide the current state of Terraform built infrastructure
name: State Resources

on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform State"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE }}

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: main/package-lock.json

      - name: Install dependencies
        run: |
          cd main
          npm install
          npm install --global cdktf-cli

      - name: CDKTF Synth
        run: |
          cd main
          cdktf synth

      - name: Terraform Init
        run: |
          cd main/cdktf.out/stacks/main
          terraform init

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Graph Architecture
        run: |
          cd main/cdktf.out/stacks/main
          terraform graph | dot -Tsvg > ../../../../graph.svg

      - name: Commit and Push graph.svg
        uses: EndBug/add-and-commit@v9
        with:
          add: graph.svg

      - name: Initialize Wiki folder
        run: |
          mkdir state
          echo "## Terraform Graph" >> state/Current-Architecture.md
          echo "![graph](https://github.com/jessewang-arvatosystems/cdktf-aws-terraform-github-actions-demo/blob/main/graph.svg)" >> state/Current-Architecture.md
          echo "## Terraform Resource List" >> state/Current-Architecture.md
          echo \`\`\` >> state/Current-Architecture.md

      - name: Terraform State List
        run: |
          cd main/cdktf.out/stacks/main
          terraform state list >> ../../../../state/Current-Architecture.md

      - run: |
          echo \`\`\` >> state/Current-Architecture.md
          echo "## Terraform Resources" >> state/Current-Architecture.md
          echo \`\`\` >> state/Current-Architecture.md

      - name: Terraform Show
        run: |
          cd main/cdktf.out/stacks/main
          terraform show -no-color >> ../../../../state/Current-Architecture.md

      - run: |
          echo \`\`\` >> state/Current-Architecture.md

      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "state"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
