# Provide the current state of Terraform built infrastructure
on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform State"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE }}

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: main/package-lock.json

      - name: Install dependencies
        run: |
          cd main
          npm install
          npm install --global cdktf-cli

      - name: CDKTF Synth
        run: |
          cd main
          cdktf synth -o ../

      - name: Terraform Init
        run: |
          cd stacks/main
          terraform init

      - name: Terraform State List
        run: |
          cd stacks/main
          terraform state list

      - name: Terraform Show
        run: |
          cd stacks/main
          terraform show
