# Runs on an open PR or open PR code update
on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Validate Terraform"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE }}

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          cd main
          npm install
          npm install --global cdktf-cli@latest

      - name: Local Test
        id: localTest
        run: |
          cd main
          npm test

#      - name: CDKTF Synth
#        run: |
#          cd main
#          cdktf synth -o ../
#
#      - name: Terraform Init
#        run: |
#          cd stacks/main
#          terraform init

      - name: Terraform Plan
        id: plan
        run: |
          cd stacks/main
          echo 'PLAN_OUTPUT<<EOF' >> $GITHUB_ENV
          cdktf diff --no-color >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            #### Terraform Plan 📖`${{ steps.plan.outcome }}`

            <details><summary>Show Plan</summary>

            ```${{ env.PLAN_OUTPUT }}
            ```

            </details>

            **Pull Request by: @${{ github.actor }}**

      - name: CDKTF Plan Status
        if: steps.plan.outcome == 'failure' || steps.localTest.outcome == 'failure'
        run: exit 1

      - run: |
          echo The Terraform build has been successfully validated
